# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# GENERAL
# ---------------------------
before:
  hooks:
    - make test
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^test:'

# ---------------------------
# BUILDER
# ---------------------------
build:
  skip: true
# ---------------------------
# Publishers
# ---------------------------
publishers:
  - name: npm
    cmd: make publish
    dir: "."
# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"
